name: Build and Deploy (Staging)

env:
  INSTANCE: Kairos
  SERVICES: flashcampus/calendar/app-stg

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.REGISTRY_USER }}/calendar
          tags: |
            type=raw,value=latest
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        id: push
        uses: docker/build-push-action@v6
        with:
          build-contexts: |
            root=.
          context: infra/docker/web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          build-args: |
            CALCOM_DIR=${{ steps.calcom-dir.outputs.path }}
            YARN_DIR=${{ steps.yarn-dir.outputs.path }}

  deploy:
    name: Trigger staging deployment
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - run: |
          REPO_OWNER=YouthCatalyst
          REPO_NAME=service-deployments
          EVENT_TYPE=trigger-workflow

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
            -d "{\"event_type\": \"$EVENT_TYPE\", \"client_payload\": {\"SERVICES\": \"${{ env.SERVICES }}\", \"INSTANCE\": \"${{ env.INSTANCE }}\"}}"